### ISSUE TITLE
hardcoded database name in database.sql

### ISSUE THREAD

**Issue by Dratone** [Pushjet/Pushjet-Server-Api#16]
Hi,

Probably due to the way you dumped it, the database.sql file has the database name (pushjet_api) hardcoded in multiple locations.

Because of this, it is needed to change the database.sql file when using a different database name.

It would be easiest for others if you dumped it without specifying the database name in the database.sql file.

**Comment by Mechazawa** [comment]
I'll be home a lot the coming week so I'll close this ASAP. Super easy fix.

-------- Original message --------From: Dratone notifications@github.com Date: 05/09/2016  20:10  (GMT+01:00) To: Pushjet/Pushjet-Server-Api Pushjet-Server-Api@noreply.github.com Subject: [Pushjet/Pushjet-Server-Api] hardcoded database name in database.sql (#16) 
Hi,

Probably due to the way you dumped it, the database.sql file has the database name (pushjet_api) hardcoded in multiple locations.

Because of this, it is needed to change the database.sql file when using a different database name.

It would be easiest for others if you dumped it without specifying the database name in the database.sql file.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Pushjet/Pushjet-Server-Api","title":"Pushjet/Pushjet-Server-Api","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Pushjet/Pushjet-Server-Api"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"hardcoded database name in database.sql (#16)"}],"action":{"name":"View Issue","url":"https://github.com/Pushjet/Pushjet-Server-Api/issues/16"}}}

**Comment by Mechazawa** [comment]
Fixed in a389bf35c1b28ba94b7b1f3e1dbbc9ca554dc8b0
