### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by Cisor** [Pushjet/Pushjet-Server-Api#27]
It looks like a great project, but doesn't seem to work in its current form. "There was a network issue" is all I get when using a service created from the documentation sample

There doesn't appear to have been any activity for many months

**Comment by Mechazawa** [comment]
It looks like my server was misconfigured for non-ssl connections over ipv4 to the pushjet api.
The project is currently on halt due to the extreem lack of time. I'm locally working on a rewrite of both the api and the app. I'm expecting to get a lot more time to work on it during summer break and in about a week.

**Comment by Cisor** [comment]
Great news! 

I'll pay close attention over the coming months
